[package]
name = "nostr-desktop"
version = "0.1.0"
edition = "2021"
description = "Nostr Desktop"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/nostr-desktop"
repository = "https://github.com/yukibtc/nostr-desktop.git"
license = "MIT"
keywords = ["nostr", "nostr-sdk", "client", "gui"]
categories = ["GUI"]

[dependencies]
async-stream = "0.3.3"
env_logger = "0.8.2"
iced = { version = "0.6", default-features = false, features = ["tokio", "wgpu"] }
iced_futures = "0.5.1"
iced_native = "0.7.0"
nostr-sdk = { git = "https://github.com/yukibtc/nostr-rs-sdk", rev = "8cba0ac22974472eb5b378bda37566eb52336d26", features = ["blocking"] }
# nostr-sdk = { path = "../nostr-rs-sdk/crates/nostr-sdk", features = ["blocking"] }
# notify-rust = "4.6.0"
tokio = { version = "1", features = ["full"] }

[profile.release]
lto = true
codegen-units = 1
strip = "debuginfo"
panic = "abort"
