[package]
name = "nostr-desktop"
version = "0.1.0"
edition = "2021"
description = "Nostr Desktop"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/nostr-desktop"
repository = "https://github.com/yukibtc/nostr-desktop.git"
license = "MIT"
keywords = ["nostr", "nostr-sdk", "client", "gui"]
categories = ["GUI"]

[dependencies]
env_logger = "0.8.2"
iced = { version = "0.6", default-features = false, features = ["wgpu"] }
iced_lazy = "0.3.0"
iced_native = "0.7.0"
nostr-sdk = { git = "https://github.com/yukibtc/nostr-rs-sdk", rev = "ef46c9242e1c92dc6e41e649824dcbffc9fad976", features = ["blocking"] }

[profile.release]
lto = true
codegen-units = 1
strip = "debuginfo"
panic = "abort"
