[package]
name = "nostr-desktop"
version = "0.1.0"
edition = "2021"
description = "Nostr Desktop"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]

[dependencies]
env_logger = "0.8.2"
iced = { version = "0.6", default-features = false, features = ["wgpu"] }
iced_lazy = "0.3.0"
iced_native = "0.7.0"
nostr-sdk = { path = "../nostr-rs-sdk/crates/nostr-sdk", features = ["blocking"] }
